### ISSUE TITLE
Repo Naming

### ISSUE THREAD

**Issue by connor-craig** [avitex/rust-dangerous#46]
Can you pls change the name of this crate to "DangeRUST" 
In its current state it is unusable.

**Comment by connor-craig** [comment]
Pls respond

**Comment by connor-craig** [comment]
Bounty Pls

**Comment by connor-craig** [comment]
@avitex has there been any progress on this? pls respond

**Comment by avitex** [comment]
Rust is safe and will always be safe. Closing as wontfix as you can't fix perfection
